version: "2"

services:
  tms:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        APP_ENV: Development
    environment:
      - ECS_CONFIG={}
    entrypoint:
      - bash
      - ./run.sh
    ports:
      - "9999:8080"
    container_name: tms

  wiremock:
    image: rodolpheche/wiremock
    ports:
      - "8888:8080"
    volumes:
      - ./mappings:/home/wiremock/mappings
      - ./__files:/home/wiremock/__files
